[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "django-db-cascade-5"
description = "PostgreSQL ON DELETE support for Django foreign keys (Django 5 only)"
readme = "README.md"
version = "0.5.0"
authors = [{ name = "Jordan Kapelner", email = "test@test.com" }]
maintainers = [{ name = "Max Frei", email = "test@test.com" }]
license = { text = "MIT" }
classifiers = [
    "Framework :: Django",
    "Framework :: Django :: 5",
    "Topic :: Database",
]
dependencies = ["Django >= 5.0, < 6.0", "psycopg >= 3.1"]

[project.urls]
"Homepage" = "http://github.com/maxfrei750/django-db-cascade-5"
"Bug Tracker" = "http://github.com/maxfrei750/django-db-cascade-5/issues"

[tool.setuptools]
zip-safe = false
